<?xml version="1.0" encoding="UTF-8"?>
<tabledefine storagename="g_car_info" ID="B692E769B7D983D3419258F1D12F1A85" name-db="g_car_info" category="" title="" author="" description="" packagename="com.jiuqi.dna.xz4.zjy.storage" name="g_car_info" isneedrebuild="false">
	<fields>
		<field dbtable="g_car_info" name="PLATE_NUM" name-db="PLATE_NUM" type="varchar(10)" primary-key="false" keep-valid="false" author="" title="车牌号" description="" ID="0C62104FE84F0C3FF01C28441EDBA341"/>
		<field dbtable="g_car_info" name="BRAND" name-db="BRAND" type="varchar(20)" primary-key="false" keep-valid="false" author="" title="品牌" description="" ID="CDE2383CA3A66D537966EF7391C9A71B"/>
		<field dbtable="g_car_info" name="MODEL" name-db="MODEL" type="varchar(50)" primary-key="false" keep-valid="false" author="" title="型号" description="" ID="5636F8C26960C5A22F8766989C6B564C"/>
		<field dbtable="g_car_info" name="IMAGE" name-db="IMAGE" type="blob" primary-key="false" keep-valid="false" author="" title="图片" description="" ID="94A571BF7029C727690326BF3A7827F1"/>
		<field dbtable="g_car_info" name="FACTORY_DATE" name-db="FACTORY_DATE" type="date" primary-key="false" keep-valid="false" author="" title="出厂日期" description="" ID="2C4898070923312B96BCFD884F1B17C4"/>
		<field dbtable="g_car_info" name="RENT_DAY" name-db="RENT_DAY" type="double" primary-key="false" keep-valid="false" author="" title="日租金" description="" ID="6A6E82FCD5ACE022C84D874A4F1726E3"/>
		<field dbtable="g_car_info" name="CAR_STATE" name-db="CAR_STATE" type="varchar(10)" primary-key="false" keep-valid="false" author="" title="车辆状态" description="" ID="34268E68FF1DD435DC09DFB28832F3CF"/>
	</fields>
	<indexs/>
	<hierarchies/>
	<dbtables>
		<dbtable author="" name="g_car_info" name-db="g_car_info" title="" description=""/>
	</dbtables>
	<relations/>
</tabledefine>
