<?xml version="1.0" encoding="UTF-8"?>
<tabledefine storagename="g_user_info" ID="173F82555538F39A84E9686FFB7F4F27" name-db="g_user_info" category="基础数据主体" title="" author="" description="" packagename="com.jiuqi.dna.xz4.zjy.storage" name="g_user_info" isneedrebuild="false">
	<fields>
		<field dbtable="g_user_info" name="account" name-db="account" type="varchar(20)" primary-key="false" keep-valid="false" author="" title="账号" description="" ID="CE34E727D77D8DA0E1E174455B944CC9"/>
		<field dbtable="g_user_info" name="accountname" name-db="accountname" type="varchar(20)" primary-key="false" keep-valid="false" author="" title="用户名" description="" ID="1CAF25B831366505C71BCE0F8735C562"/>
		<field dbtable="g_user_info" name="pass" name-db="pass" type="varchar(50)" primary-key="false" keep-valid="false" author="" title="密码" description="" ID="F5BEC8CA07A13B45F76F82BC61CE23D6"/>
		<field dbtable="g_user_info" name="mobile" name-db="mobile" type="varchar(11)" primary-key="false" keep-valid="false" author="" title="手机号码" description="" ID="902C22E302D6E795CEF2C0828D8E9E39"/>
		<field dbtable="g_user_info" name="cardNo" name-db="cardNo" type="varchar(50)" primary-key="false" keep-valid="false" author="" title="驾驶证号" description="" ID="5A35C56294602DDC8E592D29FB211825"/>
		<field dbtable="g_user_info" name="mail" name-db="mail" type="varchar(20)" primary-key="false" keep-valid="false" author="" title="邮箱" description="" ID="D68C8E75D1B0C34F319B90F38188476C"/>
	</fields>
	<indexs/>
	<hierarchies/>
	<dbtables>
		<dbtable author="" name="g_user_info" name-db="g_user_info" title="" description=""/>
	</dbtables>
	<relations/>
</tabledefine>
